#ifndef TERRAIN_RENDER_RESOURCE_H
#define TERRAIN_RENDER_RESOURCE_H



#define IDM_CAMERA_MOVE_FORWARD			100
#define IDM_CAMERA_MOVE_BACK			101
#define IDM_CAMERA_MOVE_LEFT			102
#define IDM_CAMERA_MOVE_RIGHT			103
#define IDM_CAMERA_MOVE_UP				104
#define IDM_CAMERA_MOVE_DOWN			105
#define IDM_CAMERA_ROTATE				106

#define IDM_SET_CAMERA_SPEED					110
#define IDM_SET_CAMERA_ROTATION_SPEED			111
#define IDM_SET_CAMERA_FIELD_OF_VIEW			112
#define IDM_SET_CAMERA_ASPECT_RATIO				113
#define IDM_SET_CAMERA_ASPECT_NEAR_SCREEN		114
#define IDM_SET_CAMERA_ASPECT_FAR_SCREEN		115

#define IDM_CAMERA_TRAJECTORY_NEXT_FRAME		120
#define IDM_CAMERA_TRAJECTORY_START				121
#define IDM_CAMERA_TRAJECTORY_PAUSE				122
#define IDM_CAMERA_TRAJECTORY_STOP				123


#define IDC_FIlE_TERRAIN				200
#define IDC_FIlE_CAMERA_TRAJECTORY		201
#define IDC_FIlE_CAMERA_PROPERTIES		202



//TODO: GOOD NAME FOR TJIS
#define IDC_TIME_ELLAPSED						1000

#define IDC_BUTTON_CAMERA_RESET					2000
#define IDC_SLIDER_CAMERA_SPEED					2101
#define IDC_SLIDER_CAMERA_ROTATION_SPEED		2102
#define IDC_SLIDER_PROJECTION_FIELD_OF_VIEW		2103
#define IDC_SLIDER_PROJECTION_NEAR_SCREEN		2104
#define IDC_SLIDER_PROJECTION_FAR_SCREEN		2105

#define IDC_BUTTON_FIlE_TERRAIN				3000
#define IDC_BUTTON_FIlE_CAMERA_TRAJECTORY   3001
#define IDC_BUTTON_FIlE_CAMERA_PROPERTIES	3002
//#define IDC_BUTTON_RESET                1000
//#define IDC_BUTTON_ABOUT                1001
//#define IDC_SLIDER_PITCH                1002
//#define IDC_SLIDER_YAW                  1003
//#define IDC_SLIDER_ROLL                 1004
//#define IDC_SLIDER_POSX                 1005
//#define IDC_SLIDER_POSY                 1006
//#define IDC_SLIDER_POSZ                 1007
//#define IDC_SLIDER_TARX                 1008
//#define IDC_SLIDER_TARY                 1009
//#define IDC_SLIDER_TARZ                 1010
//#define IDC_LABEL_PITCH                 1011
#endif